version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: neo4j/password
